-- DAMAY initial migration (0001) — verbatim copy of /schema.sql at repo root.
-- Generated by backend-engineer for supabase migrations.
-- DO NOT EDIT in isolation; keep this file in sync with /schema.sql.

-- =============================================================================
-- DAMAY — Postgres schema (Supabase)
-- Phase 0 deliverable. Authoritative DDL. Migrations derive from this file.
--
-- Conventions:
--   * UUID primary keys via gen_random_uuid()
--   * timestamptz everywhere, default now()
--   * snake_case columns
--   * RLS enabled on every table; default deny; explicit policies below
--   * Triggers maintain updated_at
--   * Stellar tx hashes: 64 lowercase hex; CHECK constraint enforced
--   * Cents-safe money: contribution_amount_php is INTEGER (whole pesos for v1.0)
-- =============================================================================

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------------
do $$ begin
    create type round_frequency as enum ('weekly', 'biweekly', 'monthly');
exception when duplicate_object then null; end $$;

do $$ begin
    create type round_status as enum ('draft', 'active', 'completed', 'cancelled');
exception when duplicate_object then null; end $$;

do $$ begin
    create type contribution_status as enum ('pending', 'confirmed', 'failed');
exception when duplicate_object then null; end $$;

do $$ begin
    create type payout_status as enum ('pending', 'confirmed', 'failed');
exception when duplicate_object then null; end $$;

do $$ begin
    create type message_direction as enum ('in', 'out');
exception when duplicate_object then null; end $$;

do $$ begin
    create type reputation_event_type as enum ('contribution', 'default', 'payout');
exception when duplicate_object then null; end $$;

do $$ begin
    create type stellar_job_type as enum (
        'deploy_paluwagan',
        'add_member',
        'contribute',
        'distribute_payout',
        'close_round',
        'reputation_credit',
        'reputation_default',
        'reputation_payout_received'
    );
exception when duplicate_object then null; end $$;

do $$ begin
    create type stellar_job_status as enum ('queued', 'in_flight', 'done', 'failed', 'dead_letter');
exception when duplicate_object then null; end $$;

-- ---------------------------------------------------------------------------
-- updated_at trigger
-- ---------------------------------------------------------------------------
create or replace function set_updated_at()
returns trigger language plpgsql as $$
begin
    new.updated_at = now();
    return new;
end $$;

-- ---------------------------------------------------------------------------
-- organizers
--   Linked 1:1 to auth.users.id via id column. Supabase magic-link auth fills
--   auth.users; we insert an organizers row on first sign-in.
-- ---------------------------------------------------------------------------
create table if not exists organizers (
    id uuid primary key,                       -- equals auth.users.id
    email text not null unique,
    phone text,
    display_name text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create trigger organizers_updated_at
    before update on organizers
    for each row execute function set_updated_at();

alter table organizers enable row level security;

-- organizer can read/update their own row
create policy organizers_self_select on organizers
    for select using (id = auth.uid());
create policy organizers_self_update on organizers
    for update using (id = auth.uid());
-- inserts handled by service role only (post-signup hook)
create policy organizers_service_insert on organizers
    for insert with check (auth.role() = 'service_role');

-- ---------------------------------------------------------------------------
-- members
--   No auth.users link — members never log in. Service role only.
-- ---------------------------------------------------------------------------
create table if not exists members (
    id uuid primary key default gen_random_uuid(),
    whatsapp_e164 text not null unique
        check (whatsapp_e164 ~ '^\+[1-9][0-9]{6,14}$'),
    display_name text not null,
    stellar_account text
        check (stellar_account is null or stellar_account ~ '^G[A-Z2-7]{55}$'),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists members_stellar_account_idx on members (stellar_account)
    where stellar_account is not null;

create trigger members_updated_at
    before update on members
    for each row execute function set_updated_at();

alter table members enable row level security;

-- members table is fully gated to service role; API enforces organizer access
-- on a per-round basis via the round_members join.
create policy members_service_all on members
    for all using (auth.role() = 'service_role')
    with check (auth.role() = 'service_role');

-- ---------------------------------------------------------------------------
-- rounds
-- ---------------------------------------------------------------------------
create table if not exists rounds (
    id uuid primary key default gen_random_uuid(),
    organizer_id uuid not null references organizers(id) on delete cascade,
    name text not null,
    code text not null unique
        check (char_length(code) between 4 and 16),     -- short code used in "JOIN <code>"
    contribution_amount_php integer not null check (contribution_amount_php > 0),
    member_count integer not null check (member_count between 2 and 50),
    frequency round_frequency not null,
    start_date date not null,
    status round_status not null default 'draft',
    paluwagan_contract_id text
        check (paluwagan_contract_id is null or paluwagan_contract_id ~ '^C[A-Z0-9]{55}$'),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists rounds_organizer_status_idx on rounds (organizer_id, status);
create index if not exists rounds_status_idx on rounds (status);

create trigger rounds_updated_at
    before update on rounds
    for each row execute function set_updated_at();

alter table rounds enable row level security;

create policy rounds_owner_select on rounds
    for select using (organizer_id = auth.uid());
create policy rounds_owner_insert on rounds
    for insert with check (organizer_id = auth.uid());
create policy rounds_owner_update on rounds
    for update using (organizer_id = auth.uid());
create policy rounds_owner_delete on rounds
    for delete using (organizer_id = auth.uid() and status = 'draft');
create policy rounds_service_all on rounds
    for all using (auth.role() = 'service_role')
    with check (auth.role() = 'service_role');

-- ---------------------------------------------------------------------------
-- round_members
-- ---------------------------------------------------------------------------
create table if not exists round_members (
    round_id uuid not null references rounds(id) on delete cascade,
    member_id uuid not null references members(id) on delete restrict,
    payout_position integer not null check (payout_position >= 1),
    joined_at timestamptz not null default now(),
    primary key (round_id, member_id),
    unique (round_id, payout_position)
);

create index if not exists round_members_member_idx on round_members (member_id);

alter table round_members enable row level security;

-- organizer can read round_members for their rounds
create policy round_members_owner_select on round_members
    for select using (
        exists (select 1 from rounds r where r.id = round_id and r.organizer_id = auth.uid())
    );
create policy round_members_service_all on round_members
    for all using (auth.role() = 'service_role')
    with check (auth.role() = 'service_role');

-- ---------------------------------------------------------------------------
-- contributions
-- ---------------------------------------------------------------------------
create table if not exists contributions (
    id uuid primary key default gen_random_uuid(),
    round_id uuid not null references rounds(id) on delete cascade,
    member_id uuid not null references members(id) on delete restrict,
    cycle_number integer not null check (cycle_number >= 1),
    amount_php integer not null check (amount_php > 0),
    stellar_tx_hash text
        check (stellar_tx_hash is null or stellar_tx_hash ~ '^[0-9a-f]{64}$'),
    status contribution_status not null default 'pending',
    source_message_sid text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (round_id, member_id, cycle_number)
);

create index if not exists contributions_round_cycle_idx on contributions (round_id, cycle_number);
create index if not exists contributions_member_idx on contributions (member_id);
create index if not exists contributions_status_idx on contributions (status)
    where status = 'pending';

create trigger contributions_updated_at
    before update on contributions
    for each row execute function set_updated_at();

alter table contributions enable row level security;

create policy contributions_owner_select on contributions
    for select using (
        exists (select 1 from rounds r where r.id = round_id and r.organizer_id = auth.uid())
    );
create policy contributions_service_all on contributions
    for all using (auth.role() = 'service_role')
    with check (auth.role() = 'service_role');

-- ---------------------------------------------------------------------------
-- payouts
-- ---------------------------------------------------------------------------
create table if not exists payouts (
    id uuid primary key default gen_random_uuid(),
    round_id uuid not null references rounds(id) on delete cascade,
    member_id uuid not null references members(id) on delete restrict,
    cycle_number integer not null check (cycle_number >= 1),
    amount_php integer not null check (amount_php > 0),
    stellar_tx_hash text
        check (stellar_tx_hash is null or stellar_tx_hash ~ '^[0-9a-f]{64}$'),
    status payout_status not null default 'pending',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (round_id, cycle_number)
);

create index if not exists payouts_member_idx on payouts (member_id);
create index if not exists payouts_status_idx on payouts (status)
    where status = 'pending';

create trigger payouts_updated_at
    before update on payouts
    for each row execute function set_updated_at();

alter table payouts enable row level security;

create policy payouts_owner_select on payouts
    for select using (
        exists (select 1 from rounds r where r.id = round_id and r.organizer_id = auth.uid())
    );
create policy payouts_service_all on payouts
    for all using (auth.role() = 'service_role')
    with check (auth.role() = 'service_role');

-- ---------------------------------------------------------------------------
-- messages (WhatsApp log)
-- ---------------------------------------------------------------------------
create table if not exists messages (
    id uuid primary key default gen_random_uuid(),
    member_id uuid references members(id) on delete set null,
    direction message_direction not null,
    twilio_sid text not null unique,
    body text not null,
    created_at timestamptz not null default now()
);

create index if not exists messages_member_created_idx on messages (member_id, created_at desc);

alter table messages enable row level security;

-- service role only; organizers do not read raw WhatsApp logs (PII)
create policy messages_service_all on messages
    for all using (auth.role() = 'service_role')
    with check (auth.role() = 'service_role');

-- ---------------------------------------------------------------------------
-- reputation_events
--   `context` JSONB stores arbitrary structured payload from the Soroban
--   event (e.g. round_id, cycle_number, decay_applied). Indexed only by
--   member_id + created_at; context is searched ad-hoc.
-- ---------------------------------------------------------------------------
create table if not exists reputation_events (
    id uuid primary key default gen_random_uuid(),
    member_id uuid not null references members(id) on delete cascade,
    event_type reputation_event_type not null,
    weight integer not null,
    stellar_tx_hash text not null
        check (stellar_tx_hash ~ '^[0-9a-f]{64}$'),
    context jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    unique (stellar_tx_hash, event_type)
);

create index if not exists reputation_events_member_idx on reputation_events (member_id, created_at desc);
create index if not exists reputation_events_type_idx on reputation_events (event_type);

alter table reputation_events enable row level security;

-- organizer can read reputation events for members who share a round with them
create policy reputation_events_shared_round_select on reputation_events
    for select using (
        exists (
            select 1
            from round_members rm
            join rounds r on r.id = rm.round_id
            where rm.member_id = reputation_events.member_id
              and r.organizer_id = auth.uid()
        )
    );
create policy reputation_events_service_all on reputation_events
    for all using (auth.role() = 'service_role')
    with check (auth.role() = 'service_role');

-- ---------------------------------------------------------------------------
-- idempotency_keys
--   For POST endpoints. 24h TTL enforced by nightly cleanup job.
-- ---------------------------------------------------------------------------
create table if not exists idempotency_keys (
    key text not null,
    route text not null,
    request_hash text not null,           -- sha256 of canonicalized request body
    response_status integer not null,
    response_body jsonb not null,
    created_at timestamptz not null default now(),
    expires_at timestamptz not null default (now() + interval '24 hours'),
    primary key (key, route)
);

create index if not exists idempotency_keys_expires_idx on idempotency_keys (expires_at);

alter table idempotency_keys enable row level security;

create policy idempotency_keys_service_all on idempotency_keys
    for all using (auth.role() = 'service_role')
    with check (auth.role() = 'service_role');

-- ---------------------------------------------------------------------------
-- stellar_jobs (write queue)
--   Backend never blocks an HTTP request on a chain write. Every Soroban
--   submission goes through this table; workers drain it with retries +
--   dead-letter on permanent failure.
-- ---------------------------------------------------------------------------
create table if not exists stellar_jobs (
    id uuid primary key default gen_random_uuid(),
    job_type stellar_job_type not null,
    payload jsonb not null,                   -- typed per job_type; validated by worker
    target_table text,                        -- e.g. 'contributions'
    target_id uuid,                           -- row id in target_table to update on success
    idempotency_key text,                     -- (job_type, target_id, cycle) hash, unique below
    status stellar_job_status not null default 'queued',
    attempts integer not null default 0,
    last_error text,
    stellar_tx_hash text
        check (stellar_tx_hash is null or stellar_tx_hash ~ '^[0-9a-f]{64}$'),
    scheduled_for timestamptz not null default now(),
    locked_until timestamptz,                 -- visibility timeout while in_flight
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (idempotency_key)
);

create index if not exists stellar_jobs_due_idx on stellar_jobs (status, scheduled_for)
    where status in ('queued', 'in_flight');
create index if not exists stellar_jobs_target_idx on stellar_jobs (target_table, target_id);

create trigger stellar_jobs_updated_at
    before update on stellar_jobs
    for each row execute function set_updated_at();

alter table stellar_jobs enable row level security;

create policy stellar_jobs_service_all on stellar_jobs
    for all using (auth.role() = 'service_role')
    with check (auth.role() = 'service_role');

-- ---------------------------------------------------------------------------
-- End of schema.
-- =============================================================================
